// lib/called-to-carry/questions.js
// Source of truth for all 10 assessment questions with scoring tables.
// Locked per called-to-carry-assessment-spec.md §2 (April 19, 2026).
// DO NOT modify scoring values without updating the spec first.

export const QUESTIONS = [
  {
    id: 'q1',
    text: 'In the last 90 days, how often have you woken up before your alarm with your mind already running on something you didn\'t choose to think about?',
    type: 'single_select',
    required: true,
    options: [
      { id: 'q1_a', label: 'Almost every morning',
        scores: { misaligned_builder: 3, unreleased_voice: 2, threshold: 2, aligned_builder: 0 } },
      { id: 'q1_b', label: 'A few times a week',
        scores: { misaligned_builder: 2, unreleased_voice: 2, threshold: 1, aligned_builder: 0 } },
      { id: 'q1_c', label: 'Occasionally',
        scores: { misaligned_builder: 1, unreleased_voice: 1, threshold: 1, aligned_builder: 1 } },
      { id: 'q1_d', label: 'Rarely or never',
        scores: { misaligned_builder: 0, unreleased_voice: 0, threshold: 0, aligned_builder: 3 } },
    ],
  },
  {
    id: 'q2',
    text: 'Which of these best describes how you feel about the work you are currently leading?',
    type: 'single_select',
    required: true,
    options: [
      { id: 'q2_a', label: 'It\'s exactly what I should be building. I\'m in my lane.',
        scores: { misaligned_builder: 0, unreleased_voice: 0, threshold: 0, aligned_builder: 4 } },
      { id: 'q2_b', label: 'Most of it fits, but something specific is out of order.',
        scores: { misaligned_builder: 2, unreleased_voice: 1, threshold: 1, aligned_builder: 1 } },
      { id: 'q2_c', label: 'It fit once, but it doesn\'t fit the same way anymore.',
        scores: { misaligned_builder: 3, unreleased_voice: 1, threshold: 2, aligned_builder: 0 } },
      { id: 'q2_d', label: 'I\'m not sure this is what I was meant to build at all.',
        scores: { misaligned_builder: 3, unreleased_voice: 2, threshold: 2, aligned_builder: 0 } },
      { id: 'q2_e', label: 'One season is clearly ending. The next has not taken shape.',
        scores: { misaligned_builder: 1, unreleased_voice: 1, threshold: 4, aligned_builder: 0 } },
    ],
  },
  {
    id: 'q3',
    text: 'When you think about everything you are currently responsible for — the commitments, the roles, the people who depend on you — which statement is most true?',
    type: 'single_select',
    required: true,
    options: [
      { id: 'q3_a', label: 'I\'m carrying exactly what I should be carrying.',
        scores: { misaligned_builder: 0, unreleased_voice: 0, threshold: 0, aligned_builder: 3 } },
      { id: 'q3_b', label: 'Some of what I\'m carrying used to be mine, but isn\'t anymore.',
        scores: { misaligned_builder: 4, unreleased_voice: 0, threshold: 1, aligned_builder: 0 } },
      { id: 'q3_c', label: 'I\'m carrying so much I can\'t tell what\'s mine and what isn\'t.',
        scores: { misaligned_builder: 3, unreleased_voice: 2, threshold: 1, aligned_builder: 0 } },
      { id: 'q3_d', label: 'I\'m carrying less than I should be — there\'s more in me than I\'ve released.',
        scores: { misaligned_builder: 0, unreleased_voice: 4, threshold: 1, aligned_builder: 0 } },
      { id: 'q3_e', label: 'I\'m between — I\'ve set something down, but haven\'t picked up the next thing.',
        scores: { misaligned_builder: 1, unreleased_voice: 1, threshold: 3, aligned_builder: 0 } },
    ],
  },
  {
    id: 'q4',
    text: 'Over the last year, how often have you said yes to something and regretted it within a week?',
    type: 'single_select',
    required: true,
    options: [
      { id: 'q4_a', label: 'Very often — I\'m saying yes to the wrong things on a regular basis.',
        scores: { misaligned_builder: 3, unreleased_voice: 1, threshold: 1, aligned_builder: 0 } },
      { id: 'q4_b', label: 'Sometimes — I\'m getting better but the pattern is still there.',
        scores: { misaligned_builder: 2, unreleased_voice: 1, threshold: 1, aligned_builder: 1 } },
      { id: 'q4_c', label: 'Rarely — I\'ve learned to be discerning about what I agree to.',
        scores: { misaligned_builder: 0, unreleased_voice: 0, threshold: 1, aligned_builder: 2 } },
      { id: 'q4_d', label: 'Almost never — my yes and my no are both clear.',
        scores: { misaligned_builder: 0, unreleased_voice: 0, threshold: 0, aligned_builder: 3 } },
    ],
  },
  {
    id: 'q5',
    text: 'Which of these have you tried in the last three years to get clarity on your direction? (Select all that apply.)',
    type: 'multi_select',
    required: false,
    options: [
      { id: 'q5_a', label: 'Hired a business coach or consultant',
        scores: { misaligned_builder: 1, unreleased_voice: 0, threshold: 1, aligned_builder: 0 } },
      { id: 'q5_b', label: 'Sought prophetic counsel or spiritual direction',
        scores: { misaligned_builder: 1, unreleased_voice: 1, threshold: 2, aligned_builder: 0 } },
      { id: 'q5_c', label: 'Worked with a therapist or counselor',
        scores: { misaligned_builder: 1, unreleased_voice: 1, threshold: 1, aligned_builder: 0 } },
      { id: 'q5_d', label: 'Took a sabbatical or extended time away',
        scores: { misaligned_builder: 1, unreleased_voice: 0, threshold: 2, aligned_builder: 0 } },
      { id: 'q5_e', label: 'Read extensively on leadership, calling, or strategy',
        scores: { misaligned_builder: 1, unreleased_voice: 2, threshold: 1, aligned_builder: 0 } },
      { id: 'q5_f', label: 'Attended conferences or retreats',
        scores: { misaligned_builder: 1, unreleased_voice: 1, threshold: 1, aligned_builder: 0 } },
      { id: 'q5_g', label: 'None of the above — I haven\'t sought help externally',
        scores: { misaligned_builder: 1, unreleased_voice: 2, threshold: 1, aligned_builder: 1 } },
    ],
  },
  {
    id: 'q6',
    text: 'When you hear the phrase "there\'s more in you than has come out yet," what happens inside you?',
    type: 'single_select',
    required: true,
    options: [
      { id: 'q6_a', label: 'It resonates immediately — I have sensed that for a while.',
        scores: { misaligned_builder: 1, unreleased_voice: 4, threshold: 2, aligned_builder: 0 } },
      { id: 'q6_b', label: 'It resonates, but I don\'t know what the "more" is.',
        scores: { misaligned_builder: 1, unreleased_voice: 3, threshold: 2, aligned_builder: 0 } },
      { id: 'q6_c', label: 'It makes me tired — I don\'t have capacity for more right now.',
        scores: { misaligned_builder: 2, unreleased_voice: 1, threshold: 2, aligned_builder: 0 } },
      { id: 'q6_d', label: 'It makes me uncomfortable — I can\'t tell if it\'s true or flattery.',
        scores: { misaligned_builder: 1, unreleased_voice: 2, threshold: 1, aligned_builder: 0 } },
      { id: 'q6_e', label: 'It doesn\'t resonate — I feel I am expressing what I was meant to.',
        scores: { misaligned_builder: 0, unreleased_voice: 0, threshold: 0, aligned_builder: 4 } },
    ],
  },
  {
    id: 'q7',
    text: 'In the last year, how often have you had a moment — however brief — where you sensed a quiet, clear internal nudge about a direction, a decision, or a change?',
    type: 'single_select',
    required: true,
    options: [
      { id: 'q7_a', label: 'Frequently — and I\'ve mostly not acted on them.',
        scores: { misaligned_builder: 2, unreleased_voice: 3, threshold: 3, aligned_builder: 0 } },
      { id: 'q7_b', label: 'Frequently — and I\'ve acted on most of them.',
        scores: { misaligned_builder: 0, unreleased_voice: 1, threshold: 1, aligned_builder: 3 } },
      { id: 'q7_c', label: 'Occasionally — but I\'m not sure what to do with them.',
        scores: { misaligned_builder: 1, unreleased_voice: 2, threshold: 2, aligned_builder: 1 } },
      { id: 'q7_d', label: 'Rarely — I don\'t experience that kind of prompting.',
        scores: { misaligned_builder: 1, unreleased_voice: 0, threshold: 0, aligned_builder: 1 } },
    ],
  },
  {
    id: 'q8',
    text: 'If nothing changed in the next 18 months — same work, same pace, same direction — what would that mean?',
    type: 'single_select',
    required: true,
    options: [
      { id: 'q8_a', label: 'Slow erosion — I\'d survive, but something would be lost.',
        scores: { misaligned_builder: 4, unreleased_voice: 1, threshold: 1, aligned_builder: 0 } },
      { id: 'q8_b', label: 'Quiet regret — I\'d know I missed something I was meant to do.',
        scores: { misaligned_builder: 1, unreleased_voice: 4, threshold: 1, aligned_builder: 0 } },
      { id: 'q8_c', label: 'A real crisis — financial, relational, or internal.',
        scores: { misaligned_builder: 3, unreleased_voice: 1, threshold: 2, aligned_builder: 0 } },
      { id: 'q8_d', label: 'Honestly uncertain — I can\'t see the next 18 months clearly.',
        scores: { misaligned_builder: 1, unreleased_voice: 1, threshold: 4, aligned_builder: 0 } },
      { id: 'q8_e', label: 'Steady growth — my current trajectory is aligned.',
        scores: { misaligned_builder: 0, unreleased_voice: 0, threshold: 0, aligned_builder: 4 } },
    ],
  },
  {
    id: 'q9',
    text: 'When you picture yourself 12 months from now — aligned, clear, building exactly what you were meant to build — what changes most? (Select up to two.)',
    type: 'multi_select',
    maxSelections: 2,
    required: false,
    options: [
      { id: 'q9_a', label: 'I\'ve released what was no longer mine to carry.',
        scores: { misaligned_builder: 3, unreleased_voice: 0, threshold: 1, aligned_builder: 0 } },
      { id: 'q9_b', label: 'I\'ve brought something into the world I had been carrying silently.',
        scores: { misaligned_builder: 0, unreleased_voice: 4, threshold: 1, aligned_builder: 0 } },
      { id: 'q9_c', label: 'I\'ve taken on the next assignment, and I can name it clearly.',
        scores: { misaligned_builder: 1, unreleased_voice: 1, threshold: 3, aligned_builder: 0 } },
      { id: 'q9_d', label: 'I\'m leading with peace and clarity I don\'t currently have.',
        scores: { misaligned_builder: 2, unreleased_voice: 2, threshold: 2, aligned_builder: 0 } },
      { id: 'q9_e', label: 'Nothing has changed because I\'m already there.',
        scores: { misaligned_builder: 0, unreleased_voice: 0, threshold: 0, aligned_builder: 4 } },
    ],
  },
  {
    id: 'q10',
    text: 'Last one — and be honest. What have you never said out loud to anyone, about what you sense you might be carrying or called to?',
    type: 'open_text',
    required: false,
    maxLength: 500,
    // No archetype points. Saved to assessment_submissions.private_signal.
    // Will reviews before discovery calls. Highest-signal qualitative field.
    options: [],
  },
];
