const publicPages = [
  '/login', '/auth/callback', '/auth/reset-password', '/', '/assessment',
  '/called-to-carry',
  '/called-to-carry/assessment',
  '/called-to-carry/assessment/start',
  '/called-to-carry/founders',
  '/called-to-carry/founders/apply',
  '/called-to-carry/founders/thank-you',
  '/called-to-carry/sprint',
  '/called-to-carry/sprint/apply',
  '/called-to-carry/sprint/thank-you',
  '/self-paced',
  '/self-paced/thank-you',
  '/blueprint',
  '/blueprint/apply',
  '/blueprint/thank-you',
]